SERVICE_TYPE_OPTIONS = [
    "技术上分",
    "娱乐整活",
    "甜蜜双排",
    "战术复盘",
    "新手教学",
]

ORDER_STATUS_OPTIONS = [
    "待接单",
    "已接单",
    "待确认完成",
    "已完成",
    "已取消",
    "已拒单",
    "已退款",
]

COMPLAINT_STATUS_OPTIONS = [
    "无投诉",
    "待处理",
    "处理中",
    "已解决",
    "已退款",
    "已驳回",
]

ALLOWED_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
ROLE_LABELS = {
    "player": "玩家",
    "booster": "陪玩师",
    "merchant": "商家",
    "admin": "管理员",
}
SOCIAL_PROVIDER_LABELS = {
    "wechat": "微信",
    "qq": "QQ",
}
STORE_THEME_OPTIONS = [
    ("graphite", "曜石黑"),
    ("rose", "樱粉"),
    ("sky", "天青"),
    ("violet", "霓夜紫"),
    ("mint", "薄荷绿"),
    ("candy", "蜜糖粉"),
]

DISCOVERY_GAMES = [
    {"name": "英雄联盟", "slug": "英雄联盟", "icon": "⚔", "subtitle": "双排上分 / 陪练复盘"},
    {"name": "无畏契约", "slug": "无畏契约", "icon": "✦", "subtitle": "定位赛 / 枪法教学"},
    {"name": "金铲铲之战", "slug": "金铲铲", "icon": "♜", "subtitle": "阵容教学 / 陪玩娱乐"},
    {"name": "王者荣耀", "slug": "王者荣耀", "icon": "♛", "subtitle": "连麦上分 / 情侣陪玩"},
    {"name": "CS2", "slug": "CS", "icon": "◎", "subtitle": "枪男陪玩 / 战术讲解"},
    {"name": "绝地求生", "slug": "绝地求生", "icon": "▣", "subtitle": "车队开黑 / 压枪训练"},
    {"name": "三角洲行动", "slug": "三角洲行动", "icon": "△", "subtitle": "战术小队 / 撤离陪玩"},
    {"name": "APEX", "slug": "APEX", "icon": "▲", "subtitle": "配合吃鸡 / 节奏指挥"},
    {"name": "更多游戏", "slug": "", "icon": "…", "subtitle": "小众游戏也能约"},
]

DISCOVERY_FILTER_TAGS = [
    "带妹",
    "娱乐",
    "通宵",
    "海底捞",
    "技术上分",
    "小情侣",
    "声控",
    "高分车队",
]

SHOWCASE_STORES = [
    {
        "owner_username": "club7_owner",
        "name": "第七竞技俱乐部",
        "slug": "club7",
        "theme": "rose",
        "badge": "品牌店",
        "rating": "4.9",
        "monthly_orders": "2.3k",
        "games": ["英雄联盟", "无畏契约"],
        "headline": "夜间上分专线 + 女队娱乐档",
        "description": "主打峡谷之巅双排、娱乐陪伴和包时段派单，支持急单秒回与多风格筛选。",
        "logo_path": "images/stores/club7-avatar.svg",
        "price_text": "¥69 起",
    },
    {
        "owner_username": "mist_owner",
        "name": "雾岛开黑社",
        "slug": "mist-island",
        "theme": "sky",
        "badge": "人气店",
        "rating": "4.8",
        "monthly_orders": "1.7k",
        "games": ["王者荣耀", "金铲铲之战"],
        "headline": "甜妹语音 + 双人连麦氛围场",
        "description": "更偏轻社交和陪伴体验，适合情侣档、下班娱乐和排位放松局。",
        "logo_path": "images/stores/mist-avatar.svg",
        "price_text": "¥58 起",
    },
    {
        "owner_username": "night_owner",
        "name": "夜航电竞馆",
        "slug": "night-flight",
        "theme": "violet",
        "badge": "枪战专场",
        "rating": "4.9",
        "monthly_orders": "1.2k",
        "games": ["CS2", "APEX", "绝地求生", "三角洲行动"],
        "headline": "枪男指挥团 / 车队直连",
        "description": "主打 FPS 陪练、车队联动和高分段指挥，适合想赢又想学的用户。",
        "logo_path": "images/stores/night-avatar.svg",
        "price_text": "¥88 起",
    },
    {
        "owner_username": "star_owner",
        "name": "星屿语音会馆",
        "slug": "star-voice",
        "theme": "mint",
        "badge": "精品馆",
        "rating": "4.9",
        "monthly_orders": "980",
        "games": ["英雄联盟", "金铲铲之战", "王者荣耀"],
        "headline": "高回复率 / 温柔教学 / 氛围陪伴",
        "description": "强调沟通体验和情绪价值，也支持新手入门教学与排位保姆式陪练。",
        "logo_path": "images/stores/star-avatar.svg",
        "price_text": "¥66 起",
    },
    {
        "owner_username": "aurora_owner",
        "name": "极光上分实验室",
        "slug": "aurora-lab",
        "theme": "graphite",
        "badge": "技术店",
        "rating": "4.9",
        "monthly_orders": "1.5k",
        "games": ["英雄联盟", "无畏契约", "CS2"],
        "headline": "高分段复盘 + 定制排位节奏",
        "description": "偏技术教练和高强度上分，支持分路打法诊断、局内决策纠偏和赛后复盘。",
        "logo_path": "images/stores/club7-avatar.svg",
        "price_text": "¥95 起",
    },
    {
        "owner_username": "ember_owner",
        "name": "余烬战术社",
        "slug": "ember-tactics",
        "theme": "violet",
        "badge": "战术店",
        "rating": "4.8",
        "monthly_orders": "1.1k",
        "games": ["王者荣耀", "金铲铲之战", "三角洲行动"],
        "headline": "车队协同 + 战术陪练",
        "description": "主打车队语音协同和战术执行，适合组队冲分、固定时段训练与娱乐连麦。",
        "logo_path": "images/stores/night-avatar.svg",
        "price_text": "¥72 起",
    },
]

SEED_MERCHANTS = [
    {
        "username": "club7_owner",
        "password": "qwer1234",
        "display_name": "第七俱乐部主理人",
    },
    {
        "username": "mist_owner",
        "password": "qwer1234",
        "display_name": "雾岛主理人",
    },
    {
        "username": "night_owner",
        "password": "qwer1234",
        "display_name": "夜航主理人",
    },
    {
        "username": "star_owner",
        "password": "qwer1234",
        "display_name": "星屿主理人",
    },
    {
        "username": "aurora_owner",
        "password": "qwer1234",
        "display_name": "极光实验室主理人",
    },
    {
        "username": "ember_owner",
        "password": "qwer1234",
        "display_name": "余烬战术社主理人",
    },
]

SEED_BOOSTERS = [
    {
        "username": "Miya软辅",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "英雄联盟 / 金铲铲之战",
            "rank": "峡谷之巅大师",
            "price": "88",
            "available_time": "每天 20:00 - 02:00",
            "play_style": "温柔沟通 / 细节教学 / 连麦陪伴",
            "intro": "擅长辅助位和双排节奏，适合新手跟练、情侣开黑和上分稳定局。",
            "store_name": "星屿语音会馆",
            "managed_by": "star_owner",
            "badge": "认证陪玩师",
            "response_time": "3 分钟内",
            "status_text": "今晚可接单",
            "cover_theme": "mint",
            "persona_tags": "甜妹,教学,双排,稳定上分",
            "display_avg_rating": "4.9",
            "display_completed_orders": "286",
            "display_total_orders": "318",
        },
    },
    {
        "username": "北川野王",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "王者荣耀",
            "rank": "巅峰 2400+",
            "price": "78",
            "available_time": "下午 14:00 - 凌晨 01:00",
            "play_style": "野核带飞 / 节奏指挥 / 娱乐不冷场",
            "intro": "适合想快速上星的用户，也接陪聊娱乐局，车队沟通流畅不摆烂。",
            "store_name": "雾岛开黑社",
            "managed_by": "mist_owner",
            "badge": "热门野王",
            "response_time": "5 分钟内",
            "status_text": "高峰排单中",
            "cover_theme": "rose",
            "persona_tags": "野王,带妹,娱乐,指挥",
            "display_avg_rating": "4.8",
            "display_completed_orders": "412",
            "display_total_orders": "463",
        },
    },
    {
        "username": "Echo教练",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "无畏契约 / CS2 / 三角洲行动",
            "rank": "Immortal 3",
            "price": "128",
            "available_time": "工作日 19:30 - 23:30",
            "play_style": "枪法复盘 / 视角纠正 / 战术陪练",
            "intro": "更偏技术教练型，适合定位赛、枪法提升和小队配合训练。",
            "store_name": "夜航电竞馆",
            "managed_by": "night_owner",
            "badge": "技术教练",
            "response_time": "10 分钟内",
            "status_text": "预约制",
            "cover_theme": "violet",
            "persona_tags": "枪男,教学,复盘,定位赛",
            "display_avg_rating": "5.0",
            "display_completed_orders": "159",
            "display_total_orders": "174",
        },
    },
    {
        "username": "鹿与霓虹",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "英雄联盟",
            "rank": "宗师 AD",
            "price": "98",
            "available_time": "每天 18:00 - 24:00",
            "play_style": "下路双排 / 情绪稳定 / 细节拉满",
            "intro": "偏成熟耐心型，适合下路二人组双排，擅长边打边讲思路。",
            "store_name": "第七竞技俱乐部",
            "managed_by": "club7_owner",
            "badge": "王牌 AD",
            "response_time": "2 分钟内",
            "status_text": "在线接单",
            "cover_theme": "sky",
            "persona_tags": "下路,双排,教学,温柔",
            "display_avg_rating": "4.9",
            "display_completed_orders": "337",
            "display_total_orders": "381",
        },
    },
    {
        "username": "黑糖狙神",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "绝地求生 / APEX / 三角洲行动",
            "rank": "大师车队位",
            "price": "118",
            "available_time": "周末全天 / 工作日晚间",
            "play_style": "车队协同 / 吃鸡节奏 / 压枪指导",
            "intro": "偏竞技和车队型，适合想体验高质量配合和语音指挥的用户。",
            "store_name": "夜航电竞馆",
            "managed_by": "night_owner",
            "badge": "车队核心",
            "response_time": "8 分钟内",
            "status_text": "今晚有车队",
            "cover_theme": "graphite",
            "persona_tags": "车队,枪男,吃鸡,指挥",
            "display_avg_rating": "4.8",
            "display_completed_orders": "221",
            "display_total_orders": "259",
        },
    },
    {
        "username": "奶糖兔兔",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "金铲铲之战 / 王者荣耀",
            "rank": "大师 / 荣耀王者",
            "price": "66",
            "available_time": "下午 16:00 - 晚上 23:00",
            "play_style": "轻松陪玩 / 情侣开黑 / 上分不高压",
            "intro": "更偏舒服陪伴和松弛感氛围，适合想找固定搭子长期约单的用户。",
            "store_name": "雾岛开黑社",
            "managed_by": "mist_owner",
            "badge": "人气甜妹",
            "response_time": "1 分钟内",
            "status_text": "秒回",
            "cover_theme": "candy",
            "persona_tags": "甜妹,情侣,娱乐,长期搭子",
            "display_avg_rating": "4.9",
            "display_completed_orders": "504",
            "display_total_orders": "566",
        },
    },
    {
        "username": "雨眠打野",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "英雄联盟 / 无畏契约",
            "rank": "宗师打野 / Ascendant",
            "price": "136",
            "available_time": "每天 19:00 - 01:00",
            "play_style": "节奏带动 / 资源规划 / 对局复盘",
            "intro": "偏高强度上分和节奏教学，适合冲段、定位赛与配合训练。",
            "store_name": "第七竞技俱乐部",
            "managed_by": "club7_owner",
            "badge": "节奏野核",
            "response_time": "4 分钟内",
            "status_text": "晚高峰在线",
            "cover_theme": "rose",
            "persona_tags": "打野,上分,复盘,节奏",
            "display_avg_rating": "4.9",
            "display_completed_orders": "268",
            "display_total_orders": "299",
        },
    },
    {
        "username": "青雾法刺",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "英雄联盟",
            "rank": "王者中单",
            "price": "74",
            "available_time": "下午 15:00 - 晚上 22:30",
            "play_style": "中野联动 / 稳定上分 / 连麦沟通",
            "intro": "适合想补中路细节和上分节奏的玩家，讲解清晰不催促。",
            "store_name": "第七竞技俱乐部",
            "managed_by": "club7_owner",
            "badge": "中路专精",
            "response_time": "6 分钟内",
            "status_text": "可快速接单",
            "cover_theme": "rose",
            "persona_tags": "中单,教学,双排,稳定",
            "display_avg_rating": "4.8",
            "display_completed_orders": "214",
            "display_total_orders": "246",
        },
    },
    {
        "username": "糖纸射手",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "无畏契约 / 英雄联盟",
            "rank": "Ascendant 2 / 大师",
            "price": "92",
            "available_time": "每天 18:30 - 00:30",
            "play_style": "双排连麦 / 枪线细节 / 情绪稳定",
            "intro": "偏耐心沟通和细节纠正，适合想在轻松氛围中稳定涨分。",
            "store_name": "第七竞技俱乐部",
            "managed_by": "club7_owner",
            "badge": "双修射手",
            "response_time": "3 分钟内",
            "status_text": "在线排单",
            "cover_theme": "rose",
            "persona_tags": "射手,双排,连麦,稳定",
            "display_avg_rating": "4.9",
            "display_completed_orders": "301",
            "display_total_orders": "340",
        },
    },
    {
        "username": "晚风边路",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "王者荣耀 / 金铲铲之战",
            "rank": "荣耀王者 90 星",
            "price": "58",
            "available_time": "每天 17:00 - 23:30",
            "play_style": "轻松陪玩 / 双排上星 / 语音互动",
            "intro": "更偏陪伴和放松上分，适合下班后娱乐排位或固定双排。",
            "store_name": "雾岛开黑社",
            "managed_by": "mist_owner",
            "badge": "边路暖男",
            "response_time": "2 分钟内",
            "status_text": "秒接单",
            "cover_theme": "sky",
            "persona_tags": "边路,娱乐,双排,连麦",
            "display_avg_rating": "4.8",
            "display_completed_orders": "356",
            "display_total_orders": "402",
        },
    },
    {
        "username": "果冻法王",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "金铲铲之战 / 王者荣耀",
            "rank": "金铲铲王者",
            "price": "63",
            "available_time": "中午 12:00 - 晚上 21:00",
            "play_style": "阵容讲解 / 欢乐开黑 / 新手友好",
            "intro": "擅长阵容运营与思路拆解，适合新手入门和休闲娱乐局。",
            "store_name": "雾岛开黑社",
            "managed_by": "mist_owner",
            "badge": "阵容导师",
            "response_time": "4 分钟内",
            "status_text": "白天可约",
            "cover_theme": "sky",
            "persona_tags": "金铲铲,教学,娱乐,轻松",
            "display_avg_rating": "4.9",
            "display_completed_orders": "289",
            "display_total_orders": "325",
        },
    },
    {
        "username": "枝枝软辅",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "王者荣耀 / 英雄联盟",
            "rank": "王者辅助",
            "price": "82",
            "available_time": "每天 20:00 - 01:30",
            "play_style": "语音陪伴 / 情绪价值 / 稳定沟通",
            "intro": "偏舒适沟通和陪伴体验，适合情侣双排和长期固定搭子。",
            "store_name": "雾岛开黑社",
            "managed_by": "mist_owner",
            "badge": "人气软辅",
            "response_time": "1 分钟内",
            "status_text": "今晚满电",
            "cover_theme": "sky",
            "persona_tags": "软辅,甜妹,情侣,陪伴",
            "display_avg_rating": "4.9",
            "display_completed_orders": "478",
            "display_total_orders": "533",
        },
    },
    {
        "username": "岚山突击",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "CS2 / 无畏契约",
            "rank": "Faceit Lv10",
            "price": "166",
            "available_time": "工作日 20:00 - 24:00",
            "play_style": "枪线教学 / 预瞄纠正 / 战术执行",
            "intro": "偏竞技高强度教学，适合想系统提升枪法和战术执行力的用户。",
            "store_name": "夜航电竞馆",
            "managed_by": "night_owner",
            "badge": "王牌突击",
            "response_time": "7 分钟内",
            "status_text": "预约优先",
            "cover_theme": "violet",
            "persona_tags": "枪男,教学,战术,复盘",
            "display_avg_rating": "4.9",
            "display_completed_orders": "193",
            "display_total_orders": "221",
        },
    },
    {
        "username": "白昼侦察",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "绝地求生 / 三角洲行动",
            "rank": "王牌侦察",
            "price": "108",
            "available_time": "每天 13:00 - 18:00",
            "play_style": "信息位指挥 / 车队协同 / 压枪陪练",
            "intro": "适合四排车队配合训练，擅长转点决策和信息收集。",
            "store_name": "夜航电竞馆",
            "managed_by": "night_owner",
            "badge": "侦察核心",
            "response_time": "9 分钟内",
            "status_text": "白天车队场",
            "cover_theme": "violet",
            "persona_tags": "吃鸡,车队,指挥,压枪",
            "display_avg_rating": "4.8",
            "display_completed_orders": "238",
            "display_total_orders": "271",
        },
    },
    {
        "username": "雾夜枪痕",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "APEX / CS2",
            "rank": "大师",
            "price": "132",
            "available_time": "每天 18:00 - 23:59",
            "play_style": "冲分节奏 / 枪位分工 / 语音协作",
            "intro": "偏快节奏冲分和战术分工，适合双排三排固定车队。",
            "store_name": "夜航电竞馆",
            "managed_by": "night_owner",
            "badge": "冲分枪核",
            "response_time": "6 分钟内",
            "status_text": "冲分专场",
            "cover_theme": "violet",
            "persona_tags": "APEX,冲分,枪男,协作",
            "display_avg_rating": "4.8",
            "display_completed_orders": "265",
            "display_total_orders": "298",
        },
    },
    {
        "username": "绵绵琴心",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "英雄联盟 / 王者荣耀",
            "rank": "大师辅助",
            "price": "72",
            "available_time": "每天 19:00 - 00:00",
            "play_style": "温柔陪伴 / 双排节奏 / 细节提醒",
            "intro": "主打轻松连麦和温柔沟通，适合情绪价值与稳定上分兼顾。",
            "store_name": "星屿语音会馆",
            "managed_by": "star_owner",
            "badge": "暖心辅助",
            "response_time": "2 分钟内",
            "status_text": "在线陪玩",
            "cover_theme": "mint",
            "persona_tags": "甜妹,双排,陪伴,辅助",
            "display_avg_rating": "4.9",
            "display_completed_orders": "392",
            "display_total_orders": "438",
        },
    },
    {
        "username": "小满上单",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "英雄联盟",
            "rank": "峡谷宗师",
            "price": "96",
            "available_time": "每天 16:30 - 23:00",
            "play_style": "对线细节 / 兵线运营 / 团战站位",
            "intro": "偏教学向上单陪练，适合想提升细节但不想高压训练的用户。",
            "store_name": "星屿语音会馆",
            "managed_by": "star_owner",
            "badge": "上路导师",
            "response_time": "5 分钟内",
            "status_text": "可预约",
            "cover_theme": "mint",
            "persona_tags": "上单,教学,对线,复盘",
            "display_avg_rating": "4.8",
            "display_completed_orders": "244",
            "display_total_orders": "279",
        },
    },
    {
        "username": "软糖中辅",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "金铲铲之战 / 英雄联盟",
            "rank": "宗师",
            "price": "54",
            "available_time": "每天 14:00 - 20:30",
            "play_style": "新手教学 / 氛围陪伴 / 阵容讲解",
            "intro": "适合新手用户和休闲玩家，沟通友好、节奏舒适。",
            "store_name": "星屿语音会馆",
            "managed_by": "star_owner",
            "badge": "新手友好",
            "response_time": "3 分钟内",
            "status_text": "下午场开放",
            "cover_theme": "mint",
            "persona_tags": "新手,教学,娱乐,轻松",
            "display_avg_rating": "4.9",
            "display_completed_orders": "331",
            "display_total_orders": "377",
        },
    },
    {
        "username": "苍穹哨兵",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "无畏契约 / CS2",
            "rank": "Immortal 2",
            "price": "172",
            "available_time": "每天 20:00 - 01:00",
            "play_style": "战术拆解 / 枪线协同 / 高强度复盘",
            "intro": "适合冲分和战术训练需求，偏系统化提升而非纯娱乐。",
            "store_name": "极光上分实验室",
            "managed_by": "aurora_owner",
            "badge": "战术分析师",
            "response_time": "8 分钟内",
            "status_text": "高分段场",
            "cover_theme": "graphite",
            "persona_tags": "战术,教学,高分,枪男",
            "display_avg_rating": "5.0",
            "display_completed_orders": "187",
            "display_total_orders": "209",
        },
    },
    {
        "username": "南栀打点",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "英雄联盟 / 无畏契约",
            "rank": "王者 / Ascendant",
            "price": "118",
            "available_time": "每天 18:00 - 23:30",
            "play_style": "思路讲解 / 节奏把控 / 局后复盘",
            "intro": "平衡教学和陪玩体验，适合想提升胜率与决策能力的用户。",
            "store_name": "极光上分实验室",
            "managed_by": "aurora_owner",
            "badge": "上分顾问",
            "response_time": "5 分钟内",
            "status_text": "今日可约",
            "cover_theme": "graphite",
            "persona_tags": "上分,教学,复盘,连麦",
            "display_avg_rating": "4.9",
            "display_completed_orders": "276",
            "display_total_orders": "307",
        },
    },
    {
        "username": "冷萤狙位",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "CS2 / 三角洲行动",
            "rank": "大师狙击",
            "price": "144",
            "available_time": "工作日 19:30 - 24:00",
            "play_style": "狙位讲解 / 角度控制 / 信息协同",
            "intro": "偏进阶狙位教学和团队协同，适合固定队训练。",
            "store_name": "极光上分实验室",
            "managed_by": "aurora_owner",
            "badge": "狙位导师",
            "response_time": "7 分钟内",
            "status_text": "晚间可接",
            "cover_theme": "graphite",
            "persona_tags": "狙击,教学,协同,高端局",
            "display_avg_rating": "4.8",
            "display_completed_orders": "162",
            "display_total_orders": "191",
        },
    },
    {
        "username": "雾港副攻",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "英雄联盟 / 王者荣耀",
            "rank": "大师",
            "price": "86",
            "available_time": "每天 15:00 - 22:00",
            "play_style": "双排陪练 / 细节提醒 / 沟通稳定",
            "intro": "偏双排陪练路线，节奏平稳、互动积极，适合长期固定约单。",
            "store_name": "极光上分实验室",
            "managed_by": "aurora_owner",
            "badge": "副攻位",
            "response_time": "4 分钟内",
            "status_text": "下午在线",
            "cover_theme": "graphite",
            "persona_tags": "双排,陪练,稳定,沟通",
            "display_avg_rating": "4.9",
            "display_completed_orders": "329",
            "display_total_orders": "365",
        },
    },
    {
        "username": "赤霄野核",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "王者荣耀 / 三角洲行动",
            "rank": "巅峰 2500+",
            "price": "126",
            "available_time": "每天 19:00 - 01:30",
            "play_style": "野核带节奏 / 指挥沟通 / 冲分协作",
            "intro": "适合想冲段的玩家，打法激进但沟通清晰，能带动团队节奏。",
            "store_name": "余烬战术社",
            "managed_by": "ember_owner",
            "badge": "野核核心",
            "response_time": "5 分钟内",
            "status_text": "冲分模式",
            "cover_theme": "violet",
            "persona_tags": "野王,指挥,冲分,车队",
            "display_avg_rating": "4.8",
            "display_completed_orders": "305",
            "display_total_orders": "341",
        },
    },
    {
        "username": "砂糖阵法",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "金铲铲之战 / 王者荣耀",
            "rank": "金铲铲宗师",
            "price": "48",
            "available_time": "每天 12:30 - 21:30",
            "play_style": "阵容教学 / 轻松陪玩 / 运营讲解",
            "intro": "新手友好，偏轻松娱乐和陪伴体验，也可做上分阵容纠错。",
            "store_name": "余烬战术社",
            "managed_by": "ember_owner",
            "badge": "阵容陪练",
            "response_time": "2 分钟内",
            "status_text": "白天可接",
            "cover_theme": "violet",
            "persona_tags": "金铲铲,新手,教学,娱乐",
            "display_avg_rating": "4.9",
            "display_completed_orders": "418",
            "display_total_orders": "467",
        },
    },
    {
        "username": "林间突围",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "三角洲行动 / 绝地求生",
            "rank": "战术大师",
            "price": "112",
            "available_time": "每天 18:00 - 24:00",
            "play_style": "战术跑图 / 团队协同 / 语音指挥",
            "intro": "擅长战术路线与队伍协同，适合小队长期磨合。",
            "store_name": "余烬战术社",
            "managed_by": "ember_owner",
            "badge": "战术指挥",
            "response_time": "8 分钟内",
            "status_text": "晚间小队局",
            "cover_theme": "violet",
            "persona_tags": "战术,车队,指挥,协同",
            "display_avg_rating": "4.8",
            "display_completed_orders": "207",
            "display_total_orders": "236",
        },
    },
    {
        "username": "月橙陪练",
        "password": "qwer1234",
        "role": "booster",
        "profile": {
            "games": "王者荣耀 / 英雄联盟",
            "rank": "荣耀王者",
            "price": "69",
            "available_time": "每天 16:00 - 23:00",
            "play_style": "双排陪伴 / 情绪稳定 / 沟通友好",
            "intro": "偏轻松陪伴和长线约单，适合娱乐上分两不误的用户。",
            "store_name": "余烬战术社",
            "managed_by": "ember_owner",
            "badge": "氛围担当",
            "response_time": "3 分钟内",
            "status_text": "在线等单",
            "cover_theme": "violet",
            "persona_tags": "陪伴,双排,娱乐,稳定",
            "display_avg_rating": "4.9",
            "display_completed_orders": "384",
            "display_total_orders": "429",
        },
    },
]
